FROM openjdk:11

WORKDIR /app
COPY . /app

RUN javac /app/trabalho05/trabalho05-2/src/br/unicamp/ic/inf335/OlaUnicamp.java
CMD ["java", "/app/trabalho05/trabalho05-2/src/br/unicamp/ic/inf335/OlaUnicamp.java"]
