pipeline {
    agent any

    environment {
        DOCKER_IMAGE = 'olaunicamp:latest'
    }

    stages {
        stage('Checkout') {
            steps {
                // Checkout the code from the version control
                checkout scm
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    // Build the Docker image
                    sh 'docker build -f trabalho05/trabalho05-2/Dockerfile -t ${DOCKER_IMAGE} .'
                }
            }
        }

        stage('Run Application') {
            steps {
                script {
                    // Run the Docker container
                    sh 'docker run --rm ${DOCKER_IMAGE}'
                }
            }
        }
    }

    post {
        always {
            // Clean up workspace after the build
            cleanWs()
        }
        success {
            // Notify if the build was successful
            echo 'Build and execution were successful!'
        }
        failure {
            // Notify if the build failed
            echo 'Build or execution failed!'
        }
    }
}
