version: '3.8'

services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    ports:
      - "8088:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    user: root
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
    command: >
      /bin/bash -c "
      apt-get update && 
      apt-get install -y docker.io && 
      usermod -aG docker jenkins && 
      chown jenkins:docker /var/run/docker.sock &&
      su - jenkins -c '/usr/local/bin/jenkins.sh'
      "

volumes:
  jenkins_home:
